name: flask_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask
  - rdkit
  - numpy
  - pandas
  - scikit-learn=1.6.1
  - lightgbm
  - catboost
  - tensorflow
  - tqdm
  - requests
  - gunicorn
  - pip
  - pip:
      - shap
      - plotly
      - joblib

